# Generated by Django 4.2.8 on 2024-01-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='course',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='mini_schedule',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='courses.course')),
                ('mini_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='courses.minischedule')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='courses.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='courses.usercourse'),
        ),
    ]
