# Generated by Django 4.2.8 on 2024-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
