# Generated by Django 4.2.8 on 2024-01-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_category_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
