# Generated by Django 4.2.8 on 2024-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
