# Generated by Django 4.2.8 on 2024-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project',
            field=models.BooleanField(default=False),
        ),
    ]
